services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq_distributed_tx'
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Managment UI
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  course-service:
    build:
      context: .
      dockerfile: CourseService/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  enrollment-service:
    build:
      context: .
      dockerfile: EnrollmentService/Dockerfile
    ports:
      - "5002:80"
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  notification-service:
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    ports:
      - "5003:80"
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80   